export const jobs = [{
    id: 1,
    name: '金融产品经理',
    minSalary: '10K',
    maxSalary: '20K',
    company: '中顺',
    finance: '不需要融资',
    address: '阿拉善',
    experience: '经验不限',
    education: '学历不限',
    avatar: '',
    publisher: '付莹莹.发布人'
}, {
    id: 2,
    name: '销售代表',
    minSalary: '15K',
    maxSalary: '20K',
    company: '易如歌科技',
    finance: '未融资',
    address: '阿拉善',
    experience: '1-3年',
    education: '本科',
    avatar: '',
    publisher: '付莹莹.发布人'
}, {
    id: 3,
    name: '全职教师',
    minSalary: '6K',
    maxSalary: '15K',
    company: '海风教育',
    finance: 'C轮',
    address: '阿拉善',
    experience: '经验不限',
    education: '学历不限',
    avatar: '',
    publisher: '付莹莹.发布人'
}]