export const flatlistData = [{
    id: 1,
    name: '直接费',
    des: '描述内容',
    percent: '0.1',
    quarter: '第一季度',
    money: 323432.1
}, {
    id: 2,
    name: '人工费',
    des: '描述内容',
    percent: '0.16',
    quarter: '第二季度',
    money: 338882.12
}, {
    id: 3,
    name: '材料费',
    des: '描述内容',
    percent: '0.3',
    quarter: '第三季度',
    money: 23.3
}, {
    id: 4,
    name: '机械费',
    des: '描述内容',
    quarter: '第四季度',
    percent: '0.4',
    money: 66.11
}, {
    id: 5,
    name: '会员费',
    des: '描述内容。。',
    quarter: '第一季度',
    percent: '0.1',
    money: 99.99
}, {
    id: 6,
    name: '清洁费',
    des: '描述内容',
    quarter: '第三季度',
    percent: '0.53',
    money: 2235.12
}, {
    id: 7,
    name: '物业费',
    des: '描述内容',
    quarter: '第二季度',
    percent: '0.12',
    money: 2343.45
}, {
    id: 8,
    name: '材料费',
    des: '描述内容',
    percent: '0.3',
    quarter: '第三季度',
    money: 23.3
}, {
    id: 9,
    name: '机械费',
    des: '描述内容',
    quarter: '第四季度',
    percent: '0.4',
    money: 66.11
}, {
    id: 10,
    name: '会员费',
    des: '描述内容。。',
    quarter: '第一季度',
    percent: '0.1',
    money: 99.99
}]